var username="tromoSM" //github username
var profile_description="" //leave blank to use github description
var icotheme="ffffff" //must me hex do not include whatever u call "#"
var tromoSM_icotheme="white" //leave blank for default | set value to "white" or "light" --case insetive btw
var custom_pfp={usage:false,url:""} //set usage to true if u wanna use a custom pfp and set url to custom url 
var favicon={default:true,url:""}//set deafult to false if u wanna have a custom icon

var PROFILE_LINK = "https://github.com/tromoSM" //link when the pfp is clicked
var PROFILE_LINK_DES="Github profile" //what does the profile link open 
var GITHUB="https://github.com/tromoSM" 
var LINKTREE="https://linkTr.ee/TromoSM" 
var INSTAGRAM="https://instagram.com/tromoSM" 
var X="https://x.com/tromoSM"
var THREADS="https://www.threads.com/tromoSM"
var GMAIL="mailto:tromosm.business@gmail.com"
var LINKEDIN="https://www.linkedin.com/in/tromoSM"
var BUYMEACOFFEE="https://buymeacoffee.com/tromosm"
var PONTOON="https://pontoon.mozilla.org/contributors/czwiZRZhsQKfq6_a1Dy2r_PnkUM"
var SM$PY="https://github.com/tromoSM/SM.S-PY" //personal
var MOZILLA_SUPPORT="https://support.mozilla.org/en-US/user/tromoSM/"
